package edu.fiuba.algo3.entrega_2;


import edu.fiuba.algo3.modelo.Message;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import edu.fiuba.algo3.models.Jugador;

public class Prueba {
    @Test
    public void Prueba01(){
        Jugador prueba=new Jugador();
        assertTrue(prueba.Creditos=100);
        assertTrue(prueba.Vida=20);

    }
}